catalog:
  hono: 4.12.18

overrides:
  "react-router-hono-server@2>hono": "catalog:"

onlyBuiltDependencies:
  - "@biomejs/biome"
  - "@tailwindcss/oxide"
  - "esbuild"
  - "msw"

allowBuilds:
  esbuild: true
