query GetPost($slug: String!, $format: PostTextFormatsInput) {
  post(slug: $slug) {
    id
    title
    slug
    text(format: $format)
    isDraft

    creator {
      id
      login
      name {
        first
        last
      }
    }

    dates {
      createdAt
      updatedAt
      deletedAt
    }
  }
}
