query GetPosts($page: Int) {
  posts(page: $page) {
    hasNext
    last
    count
    limit
    current
    offset

    list {
      id
      title
      slug
      isDraft

      author {
        id
        login
        name
      }

      dates {
        createdAt
        updatedAt
        deletedAt
      }
    }
  }
}
