import {
  Entity,
  Property,
  ManyToOne,
  OptionalProps,
  JsonType
} from "@mikro-orm/core"

import type {OPostCreateInput} from "server/trpc/type/input/PostCreateInput"
import type {OEditorData} from "server/trpc/type/common/EditorData"

import {BaseDates, OptionalDates} from "./BaseDates"
import {User} from "./User"

@Entity()
export class Post extends BaseDates implements OPostCreateInput {
  [OptionalProps]?: OptionalDates | "slug"

  /**
   * Post title
   */
  @Property()
  title!: string

  /**
   * Post content, generated by Slate editor
   */
  @Property({type: JsonType})
  content!: OEditorData

  /**
   * Unique, human-readable Post identifier.
   */
  @Property({unique: true})
  slug!: string

  /**
   * Post author
   */
  @ManyToOne({eager: true})
  author!: User
}
